### PR TITLE
Created workflow slack notifications template

### PR DESCRIPTION
**Pull request by courtneygreif**
This template shows how to add slack notifications to a workflow that send the first notification when the workflow begins to run, and a completion notification with the outcome of the workflow. An example of use is provided with the hello-world template. In addition, a line was added to CONTRIBUTING.md to clarify that the metadata.annotations section is required.

### CODE REVIEW

**Review by alexec — APPROVED** [review]

**Comment by alexec** [comment]
Build needs fixing.

**Comment by courtneygreif** [comment]
@alexec Regarding the build error under "Ensure there are no changes", don't changes have to be added to the index.html file that seems to be the cause of the issue? Also, the workflow run-kind-tests is calling https://raw.githubusercontent.com/argoproj/argo/v2.9.4/manifests/quick-start-minimal.yaml which doesn't exist. Does this line need to be updated at all?

**Comment by alexec** [comment]
I think you just need to delete this:

-# A hello-world example of the workflow getting notifications added to it

**Comment by alexec** [comment]
I've just corrected the URL on `master`.

**Comment by courtneygreif** [comment]
@alexec Hi, I think the workflow is awaiting approval :)

**Pull request merged**
