### PR TITLE
Container image

### PR DESCRIPTION
**Pull request by vfarcic**
Building container images using Kaniko. Additional variations will be added soon.

### CODE REVIEW

**Comment by alexec** [comment]
Please sync with master to get commit https://github.com/argoproj-labs/argo-workflows-catalog/commit/7af8769fc385bff4aedf4a356d0925e9684b4a5b to fix the build.

**Comment by alexec** [comment]
Should this be called `kaniko` rather than `container-image` as it explicitly only uses Kaniko, and we have a `buildkit` based template.

**Comment by vfarcic** [comment]
I thought to make it generic and use that template to add other ways to perform actions with container images, Kaniko being only the first example. I wasn't sure whether it makes more sense to have one with multiple variations or each (e.g., Docker, Kaniko, etc.) is better off to be separate. WDYT @alexec ?

While I have your attention... Are there any plans to expand the spec so that additional information can be added to templates.  How to use each parameter, examples, etc...

**Comment by alexec** [comment]
@vfarcic sorry - I missed this because of holidays. 

I think we should have a Kaniko specific template. I think people tend to choose this or Buildkit.


We can always add another generic template later.

**Pull request closed without merging**
